// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/app-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/app-config.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/app-config.put').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/parent-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/parent-login.post').default>>>>
    }
    '/api/redemptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redemptions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redemptions.post').default>>>>
    }
    '/api/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions.post').default>>>>
    }
    '/api/sessions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/[id].delete').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}